//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.27 at 09:19:50 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.collada.org/2005/11/COLLADASchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.collada._2005._11.colladaschema;
