//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.27 at 09:08:35 PM MESZ 
//


package org.collada._2008._03.colladaschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asset" type="{http://www.collada.org/2008/03/COLLADASchema}asset_type"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="library_animations" type="{http://www.collada.org/2008/03/COLLADASchema}library_animations_type"/>
 *           &lt;element name="library_animation_clips" type="{http://www.collada.org/2008/03/COLLADASchema}library_animation_clips_type"/>
 *           &lt;element name="library_cameras" type="{http://www.collada.org/2008/03/COLLADASchema}library_cameras_type"/>
 *           &lt;element name="library_controllers" type="{http://www.collada.org/2008/03/COLLADASchema}library_controllers_type"/>
 *           &lt;element name="library_geometries" type="{http://www.collada.org/2008/03/COLLADASchema}library_geometries_type"/>
 *           &lt;element name="library_effects" type="{http://www.collada.org/2008/03/COLLADASchema}library_effects_type"/>
 *           &lt;element name="library_force_fields" type="{http://www.collada.org/2008/03/COLLADASchema}library_force_fields_type"/>
 *           &lt;element name="library_images" type="{http://www.collada.org/2008/03/COLLADASchema}library_images_type"/>
 *           &lt;element name="library_lights" type="{http://www.collada.org/2008/03/COLLADASchema}library_lights_type"/>
 *           &lt;element name="library_materials" type="{http://www.collada.org/2008/03/COLLADASchema}library_materials_type"/>
 *           &lt;element name="library_nodes" type="{http://www.collada.org/2008/03/COLLADASchema}library_nodes_type"/>
 *           &lt;element name="library_physics_materials" type="{http://www.collada.org/2008/03/COLLADASchema}library_physics_materials_type"/>
 *           &lt;element name="library_physics_models" type="{http://www.collada.org/2008/03/COLLADASchema}library_physics_models_type"/>
 *           &lt;element name="library_physics_scenes" type="{http://www.collada.org/2008/03/COLLADASchema}library_physics_scenes_type"/>
 *           &lt;element name="library_visual_scenes" type="{http://www.collada.org/2008/03/COLLADASchema}library_visual_scenes_type"/>
 *           &lt;element name="library_joints" type="{http://www.collada.org/2008/03/COLLADASchema}library_joints_type"/>
 *           &lt;element name="library_kinematics_models" type="{http://www.collada.org/2008/03/COLLADASchema}library_kinematics_models_type"/>
 *           &lt;element name="library_articulated_systems" type="{http://www.collada.org/2008/03/COLLADASchema}library_articulated_systems_type"/>
 *           &lt;element name="library_kinematics_scenes" type="{http://www.collada.org/2008/03/COLLADASchema}library_kinematics_scenes_type"/>
 *           &lt;element name="library_formulas" type="{http://www.collada.org/2008/03/COLLADASchema}library_formulas_type"/>
 *         &lt;/choice>
 *         &lt;element name="scene" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="instance_physics_scene" type="{http://www.collada.org/2008/03/COLLADASchema}instance_with_extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="instance_visual_scene" type="{http://www.collada.org/2008/03/COLLADASchema}instance_with_extra_type" minOccurs="0"/>
 *                   &lt;element name="instance_kinematics_scene" type="{http://www.collada.org/2008/03/COLLADASchema}instance_kinematics_scene_type" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}version_enum" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "asset",
    "libraryAnimationsOrLibraryAnimationClipsOrLibraryCameras",
    "scene",
    "extra"
})
@XmlRootElement(name = "COLLADA")
public class COLLADA {

    @XmlElement(required = true)
    protected AssetType asset;
    @XmlElements({
        @XmlElement(name = "library_formulas", type = LibraryFormulasType.class),
        @XmlElement(name = "library_kinematics_scenes", type = LibraryKinematicsScenesType.class),
        @XmlElement(name = "library_controllers", type = LibraryControllersType.class),
        @XmlElement(name = "library_physics_models", type = LibraryPhysicsModelsType.class),
        @XmlElement(name = "library_joints", type = LibraryJointsType.class),
        @XmlElement(name = "library_animation_clips", type = LibraryAnimationClipsType.class),
        @XmlElement(name = "library_physics_materials", type = LibraryPhysicsMaterialsType.class),
        @XmlElement(name = "library_visual_scenes", type = LibraryVisualScenesType.class),
        @XmlElement(name = "library_animations", type = LibraryAnimationsType.class),
        @XmlElement(name = "library_cameras", type = LibraryCamerasType.class),
        @XmlElement(name = "library_geometries", type = LibraryGeometriesType.class),
        @XmlElement(name = "library_physics_scenes", type = LibraryPhysicsScenesType.class),
        @XmlElement(name = "library_articulated_systems", type = LibraryArticulatedSystemsType.class),
        @XmlElement(name = "library_effects", type = LibraryEffectsType.class),
        @XmlElement(name = "library_images", type = LibraryImagesType.class),
        @XmlElement(name = "library_materials", type = LibraryMaterialsType.class),
        @XmlElement(name = "library_nodes", type = LibraryNodesType.class),
        @XmlElement(name = "library_lights", type = LibraryLightsType.class),
        @XmlElement(name = "library_kinematics_models", type = LibraryKinematicsModelsType.class),
        @XmlElement(name = "library_force_fields", type = LibraryForceFieldsType.class)
    })
    protected List<Object> libraryAnimationsOrLibraryAnimationClipsOrLibraryCameras;
    protected COLLADA.Scene scene;
    protected List<ExtraType> extra;
    @XmlAttribute(required = true)
    protected String version;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;

    /**
     * Gets the value of the asset property.
     * 
     * @return
     *     possible object is
     *     {@link AssetType }
     *     
     */
    public AssetType getAsset() {
        return asset;
    }

    /**
     * Sets the value of the asset property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetType }
     *     
     */
    public void setAsset(AssetType value) {
        this.asset = value;
    }

    /**
     * Gets the value of the libraryAnimationsOrLibraryAnimationClipsOrLibraryCameras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the libraryAnimationsOrLibraryAnimationClipsOrLibraryCameras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLibraryAnimationsOrLibraryAnimationClipsOrLibraryCameras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LibraryFormulasType }
     * {@link LibraryKinematicsScenesType }
     * {@link LibraryControllersType }
     * {@link LibraryPhysicsModelsType }
     * {@link LibraryJointsType }
     * {@link LibraryAnimationClipsType }
     * {@link LibraryPhysicsMaterialsType }
     * {@link LibraryVisualScenesType }
     * {@link LibraryAnimationsType }
     * {@link LibraryCamerasType }
     * {@link LibraryGeometriesType }
     * {@link LibraryPhysicsScenesType }
     * {@link LibraryArticulatedSystemsType }
     * {@link LibraryEffectsType }
     * {@link LibraryImagesType }
     * {@link LibraryMaterialsType }
     * {@link LibraryNodesType }
     * {@link LibraryLightsType }
     * {@link LibraryKinematicsModelsType }
     * {@link LibraryForceFieldsType }
     * 
     * 
     */
    public List<Object> getLibraryAnimationsOrLibraryAnimationClipsOrLibraryCameras() {
        if (libraryAnimationsOrLibraryAnimationClipsOrLibraryCameras == null) {
            libraryAnimationsOrLibraryAnimationClipsOrLibraryCameras = new ArrayList<Object>();
        }
        return this.libraryAnimationsOrLibraryAnimationClipsOrLibraryCameras;
    }

    /**
     * Gets the value of the scene property.
     * 
     * @return
     *     possible object is
     *     {@link COLLADA.Scene }
     *     
     */
    public COLLADA.Scene getScene() {
        return scene;
    }

    /**
     * Sets the value of the scene property.
     * 
     * @param value
     *     allowed object is
     *     {@link COLLADA.Scene }
     *     
     */
    public void setScene(COLLADA.Scene value) {
        this.scene = value;
    }

    /**
     * Gets the value of the extra property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extra property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtra().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtraType }
     * 
     * 
     */
    public List<ExtraType> getExtra() {
        if (extra == null) {
            extra = new ArrayList<ExtraType>();
        }
        return this.extra;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * 
     * 					The xml:base attribute allows you to define the base URI for this COLLADA document. See
     * 					http://www.w3.org/TR/xmlbase/ for more information.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="instance_physics_scene" type="{http://www.collada.org/2008/03/COLLADASchema}instance_with_extra_type" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="instance_visual_scene" type="{http://www.collada.org/2008/03/COLLADASchema}instance_with_extra_type" minOccurs="0"/>
     *         &lt;element name="instance_kinematics_scene" type="{http://www.collada.org/2008/03/COLLADASchema}instance_kinematics_scene_type" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instancePhysicsScene",
        "instanceVisualScene",
        "instanceKinematicsScene",
        "extra"
    })
    public static class Scene {

        @XmlElement(name = "instance_physics_scene")
        protected List<InstanceWithExtraType> instancePhysicsScene;
        @XmlElement(name = "instance_visual_scene")
        protected InstanceWithExtraType instanceVisualScene;
        @XmlElement(name = "instance_kinematics_scene")
        protected List<InstanceKinematicsSceneType> instanceKinematicsScene;
        protected List<ExtraType> extra;

        /**
         * Gets the value of the instancePhysicsScene property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the instancePhysicsScene property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstancePhysicsScene().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InstanceWithExtraType }
         * 
         * 
         */
        public List<InstanceWithExtraType> getInstancePhysicsScene() {
            if (instancePhysicsScene == null) {
                instancePhysicsScene = new ArrayList<InstanceWithExtraType>();
            }
            return this.instancePhysicsScene;
        }

        /**
         * Gets the value of the instanceVisualScene property.
         * 
         * @return
         *     possible object is
         *     {@link InstanceWithExtraType }
         *     
         */
        public InstanceWithExtraType getInstanceVisualScene() {
            return instanceVisualScene;
        }

        /**
         * Sets the value of the instanceVisualScene property.
         * 
         * @param value
         *     allowed object is
         *     {@link InstanceWithExtraType }
         *     
         */
        public void setInstanceVisualScene(InstanceWithExtraType value) {
            this.instanceVisualScene = value;
        }

        /**
         * Gets the value of the instanceKinematicsScene property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the instanceKinematicsScene property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstanceKinematicsScene().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InstanceKinematicsSceneType }
         * 
         * 
         */
        public List<InstanceKinematicsSceneType> getInstanceKinematicsScene() {
            if (instanceKinematicsScene == null) {
                instanceKinematicsScene = new ArrayList<InstanceKinematicsSceneType>();
            }
            return this.instanceKinematicsScene;
        }

        /**
         * Gets the value of the extra property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extra property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtra().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExtraType }
         * 
         * 
         */
        public List<ExtraType> getExtra() {
            if (extra == null) {
                extra = new ArrayList<ExtraType>();
            }
            return this.extra;
        }

    }

}
