//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.27 at 09:08:35 PM MESZ 
//


package org.collada._2008._03.colladaschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Identify code fragments and bind their parameters to effect parameters to identify how their values will be filled in
 * 
 * <p>Java class for gles2_shader_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gles2_shader_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sources">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}fx_sources_type">
 *                 &lt;attribute name="entry" type="{http://www.w3.org/2001/XMLSchema}token" default="main" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="compiler" type="{http://www.collada.org/2008/03/COLLADASchema}fx_target_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="stage" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}fx_pipeline_stage_enum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gles2_shader_type", propOrder = {
    "sources",
    "compiler",
    "extra"
})
public class Gles2ShaderType {

    @XmlElement(required = true)
    protected Gles2ShaderType.Sources sources;
    protected List<FxTargetType> compiler;
    protected List<ExtraType> extra;
    @XmlAttribute(required = true)
    protected FxPipelineStageEnum stage;

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link Gles2ShaderType.Sources }
     *     
     */
    public Gles2ShaderType.Sources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gles2ShaderType.Sources }
     *     
     */
    public void setSources(Gles2ShaderType.Sources value) {
        this.sources = value;
    }

    /**
     * Gets the value of the compiler property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compiler property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompiler().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FxTargetType }
     * 
     * 
     */
    public List<FxTargetType> getCompiler() {
        if (compiler == null) {
            compiler = new ArrayList<FxTargetType>();
        }
        return this.compiler;
    }

    /**
     * Gets the value of the extra property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extra property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtra().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtraType }
     * 
     * 
     */
    public List<ExtraType> getExtra() {
        if (extra == null) {
            extra = new ArrayList<ExtraType>();
        }
        return this.extra;
    }

    /**
     * Gets the value of the stage property.
     * 
     * @return
     *     possible object is
     *     {@link FxPipelineStageEnum }
     *     
     */
    public FxPipelineStageEnum getStage() {
        return stage;
    }

    /**
     * Sets the value of the stage property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxPipelineStageEnum }
     *     
     */
    public void setStage(FxPipelineStageEnum value) {
        this.stage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}fx_sources_type">
     *       &lt;attribute name="entry" type="{http://www.w3.org/2001/XMLSchema}token" default="main" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Sources
        extends FxSourcesType
    {

        @XmlAttribute
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String entry;

        /**
         * Gets the value of the entry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntry() {
            if (entry == null) {
                return "main";
            } else {
                return entry;
            }
        }

        /**
         * Sets the value of the entry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntry(String value) {
            this.entry = value;
        }

    }

}
