//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.27 at 09:08:35 PM MESZ 
//


package org.collada._2008._03.colladaschema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for image_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="image_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asset" type="{http://www.collada.org/2008/03/COLLADASchema}asset_type" minOccurs="0"/>
 *         &lt;element name="renderable" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="share" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="init_from">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
 *                   &lt;attribute name="mips_generate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="create_2d">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;choice>
 *                       &lt;element name="size_exact">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                               &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                       &lt;element name="size_ratio">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                               &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                     &lt;/choice>
 *                     &lt;choice>
 *                       &lt;element name="mips" type="{http://www.collada.org/2008/03/COLLADASchema}image_mips_type"/>
 *                       &lt;element name="unnormalized" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                     &lt;/choice>
 *                     &lt;element name="array" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="format" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="hint">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
 *                                       &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
 *                                       &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
 *                                       &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="init_from" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
 *                             &lt;attribute name="mip_index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                             &lt;attribute name="array_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="create_3d">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="size">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                             &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                             &lt;attribute name="depth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="mips" type="{http://www.collada.org/2008/03/COLLADASchema}image_mips_type"/>
 *                     &lt;element name="array" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="format" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="hint">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
 *                                       &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
 *                                       &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
 *                                       &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="init_from" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
 *                             &lt;attribute name="depth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                             &lt;attribute name="mip_index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                             &lt;attribute name="array_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="create_cube">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="size">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="mips" type="{http://www.collada.org/2008/03/COLLADASchema}image_mips_type"/>
 *                     &lt;element name="array" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="format" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="hint">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
 *                                       &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
 *                                       &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
 *                                       &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="init_from" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
 *                             &lt;attribute name="face" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_face_enum" />
 *                             &lt;attribute name="mip_index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                             &lt;attribute name="array_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "image_type", propOrder = {
    "asset",
    "renderable",
    "initFrom",
    "create2D",
    "create3D",
    "createCube",
    "extra"
})
public class ImageType {

    protected AssetType asset;
    protected ImageType.Renderable renderable;
    @XmlElement(name = "init_from")
    protected ImageType.InitFrom initFrom;
    @XmlElement(name = "create_2d")
    protected ImageType.Create2D create2D;
    @XmlElement(name = "create_3d")
    protected ImageType.Create3D create3D;
    @XmlElement(name = "create_cube")
    protected ImageType.CreateCube createCube;
    protected List<ExtraType> extra;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sid;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;

    /**
     * Gets the value of the asset property.
     * 
     * @return
     *     possible object is
     *     {@link AssetType }
     *     
     */
    public AssetType getAsset() {
        return asset;
    }

    /**
     * Sets the value of the asset property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetType }
     *     
     */
    public void setAsset(AssetType value) {
        this.asset = value;
    }

    /**
     * Gets the value of the renderable property.
     * 
     * @return
     *     possible object is
     *     {@link ImageType.Renderable }
     *     
     */
    public ImageType.Renderable getRenderable() {
        return renderable;
    }

    /**
     * Sets the value of the renderable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageType.Renderable }
     *     
     */
    public void setRenderable(ImageType.Renderable value) {
        this.renderable = value;
    }

    /**
     * Gets the value of the initFrom property.
     * 
     * @return
     *     possible object is
     *     {@link ImageType.InitFrom }
     *     
     */
    public ImageType.InitFrom getInitFrom() {
        return initFrom;
    }

    /**
     * Sets the value of the initFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageType.InitFrom }
     *     
     */
    public void setInitFrom(ImageType.InitFrom value) {
        this.initFrom = value;
    }

    /**
     * Gets the value of the create2D property.
     * 
     * @return
     *     possible object is
     *     {@link ImageType.Create2D }
     *     
     */
    public ImageType.Create2D getCreate2D() {
        return create2D;
    }

    /**
     * Sets the value of the create2D property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageType.Create2D }
     *     
     */
    public void setCreate2D(ImageType.Create2D value) {
        this.create2D = value;
    }

    /**
     * Gets the value of the create3D property.
     * 
     * @return
     *     possible object is
     *     {@link ImageType.Create3D }
     *     
     */
    public ImageType.Create3D getCreate3D() {
        return create3D;
    }

    /**
     * Sets the value of the create3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageType.Create3D }
     *     
     */
    public void setCreate3D(ImageType.Create3D value) {
        this.create3D = value;
    }

    /**
     * Gets the value of the createCube property.
     * 
     * @return
     *     possible object is
     *     {@link ImageType.CreateCube }
     *     
     */
    public ImageType.CreateCube getCreateCube() {
        return createCube;
    }

    /**
     * Sets the value of the createCube property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageType.CreateCube }
     *     
     */
    public void setCreateCube(ImageType.CreateCube value) {
        this.createCube = value;
    }

    /**
     * Gets the value of the extra property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extra property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtra().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtraType }
     * 
     * 
     */
    public List<ExtraType> getExtra() {
        if (extra == null) {
            extra = new ArrayList<ExtraType>();
        }
        return this.extra;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the sid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSid() {
        return sid;
    }

    /**
     * Sets the value of the sid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSid(String value) {
        this.sid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="size_exact">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                   &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="size_ratio">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                   &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/choice>
     *         &lt;choice>
     *           &lt;element name="mips" type="{http://www.collada.org/2008/03/COLLADASchema}image_mips_type"/>
     *           &lt;element name="unnormalized" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;/choice>
     *         &lt;element name="array" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="format" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hint">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
     *                           &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
     *                           &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
     *                           &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="init_from" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
     *                 &lt;attribute name="mip_index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                 &lt;attribute name="array_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sizeExact",
        "sizeRatio",
        "mips",
        "unnormalized",
        "array",
        "format",
        "initFrom"
    })
    public static class Create2D {

        @XmlElement(name = "size_exact")
        protected ImageType.Create2D.SizeExact sizeExact;
        @XmlElement(name = "size_ratio")
        protected ImageType.Create2D.SizeRatio sizeRatio;
        protected ImageMipsType mips;
        protected Object unnormalized;
        protected ImageType.Create2D.Array array;
        protected ImageType.Create2D.Format format;
        @XmlElement(name = "init_from")
        protected List<ImageType.Create2D.InitFrom> initFrom;

        /**
         * Gets the value of the sizeExact property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.Create2D.SizeExact }
         *     
         */
        public ImageType.Create2D.SizeExact getSizeExact() {
            return sizeExact;
        }

        /**
         * Sets the value of the sizeExact property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.Create2D.SizeExact }
         *     
         */
        public void setSizeExact(ImageType.Create2D.SizeExact value) {
            this.sizeExact = value;
        }

        /**
         * Gets the value of the sizeRatio property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.Create2D.SizeRatio }
         *     
         */
        public ImageType.Create2D.SizeRatio getSizeRatio() {
            return sizeRatio;
        }

        /**
         * Sets the value of the sizeRatio property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.Create2D.SizeRatio }
         *     
         */
        public void setSizeRatio(ImageType.Create2D.SizeRatio value) {
            this.sizeRatio = value;
        }

        /**
         * Gets the value of the mips property.
         * 
         * @return
         *     possible object is
         *     {@link ImageMipsType }
         *     
         */
        public ImageMipsType getMips() {
            return mips;
        }

        /**
         * Sets the value of the mips property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageMipsType }
         *     
         */
        public void setMips(ImageMipsType value) {
            this.mips = value;
        }

        /**
         * Gets the value of the unnormalized property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getUnnormalized() {
            return unnormalized;
        }

        /**
         * Sets the value of the unnormalized property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setUnnormalized(Object value) {
            this.unnormalized = value;
        }

        /**
         * Gets the value of the array property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.Create2D.Array }
         *     
         */
        public ImageType.Create2D.Array getArray() {
            return array;
        }

        /**
         * Sets the value of the array property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.Create2D.Array }
         *     
         */
        public void setArray(ImageType.Create2D.Array value) {
            this.array = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.Create2D.Format }
         *     
         */
        public ImageType.Create2D.Format getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.Create2D.Format }
         *     
         */
        public void setFormat(ImageType.Create2D.Format value) {
            this.format = value;
        }

        /**
         * Gets the value of the initFrom property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the initFrom property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInitFrom().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageType.Create2D.InitFrom }
         * 
         * 
         */
        public List<ImageType.Create2D.InitFrom> getInitFrom() {
            if (initFrom == null) {
                initFrom = new ArrayList<ImageType.Create2D.InitFrom>();
            }
            return this.initFrom;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Array {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger length;

            /**
             * Gets the value of the length property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getLength() {
                return length;
            }

            /**
             * Sets the value of the length property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setLength(BigInteger value) {
                this.length = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hint">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
         *                 &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
         *                 &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
         *                 &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hint",
            "exact"
        })
        public static class Format {

            @XmlElement(required = true)
            protected ImageType.Create2D.Format.Hint hint;
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String exact;

            /**
             * Gets the value of the hint property.
             * 
             * @return
             *     possible object is
             *     {@link ImageType.Create2D.Format.Hint }
             *     
             */
            public ImageType.Create2D.Format.Hint getHint() {
                return hint;
            }

            /**
             * Sets the value of the hint property.
             * 
             * @param value
             *     allowed object is
             *     {@link ImageType.Create2D.Format.Hint }
             *     
             */
            public void setHint(ImageType.Create2D.Format.Hint value) {
                this.hint = value;
            }

            /**
             * Gets the value of the exact property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExact() {
                return exact;
            }

            /**
             * Sets the value of the exact property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExact(String value) {
                this.exact = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
             *       &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
             *       &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
             *       &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Hint {

                @XmlAttribute(required = true)
                protected ImageFormatHintChannelsEnum channels;
                @XmlAttribute(required = true)
                protected ImageFormatHintRangeEnum range;
                @XmlAttribute
                protected ImageFormatHintPrecisionEnum precision;
                @XmlAttribute
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "token")
                protected String space;

                /**
                 * Gets the value of the channels property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ImageFormatHintChannelsEnum }
                 *     
                 */
                public ImageFormatHintChannelsEnum getChannels() {
                    return channels;
                }

                /**
                 * Sets the value of the channels property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ImageFormatHintChannelsEnum }
                 *     
                 */
                public void setChannels(ImageFormatHintChannelsEnum value) {
                    this.channels = value;
                }

                /**
                 * Gets the value of the range property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ImageFormatHintRangeEnum }
                 *     
                 */
                public ImageFormatHintRangeEnum getRange() {
                    return range;
                }

                /**
                 * Sets the value of the range property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ImageFormatHintRangeEnum }
                 *     
                 */
                public void setRange(ImageFormatHintRangeEnum value) {
                    this.range = value;
                }

                /**
                 * Gets the value of the precision property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ImageFormatHintPrecisionEnum }
                 *     
                 */
                public ImageFormatHintPrecisionEnum getPrecision() {
                    if (precision == null) {
                        return ImageFormatHintPrecisionEnum.DEFAULT;
                    } else {
                        return precision;
                    }
                }

                /**
                 * Sets the value of the precision property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ImageFormatHintPrecisionEnum }
                 *     
                 */
                public void setPrecision(ImageFormatHintPrecisionEnum value) {
                    this.precision = value;
                }

                /**
                 * Gets the value of the space property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSpace() {
                    return space;
                }

                /**
                 * Sets the value of the space property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSpace(String value) {
                    this.space = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
         *       &lt;attribute name="mip_index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *       &lt;attribute name="array_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class InitFrom
            extends ImageSourceType
        {

            @XmlAttribute(name = "mip_index", required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long mipIndex;
            @XmlAttribute(name = "array_index")
            @XmlSchemaType(name = "unsignedInt")
            protected Long arrayIndex;

            /**
             * Gets the value of the mipIndex property.
             * 
             */
            public long getMipIndex() {
                return mipIndex;
            }

            /**
             * Sets the value of the mipIndex property.
             * 
             */
            public void setMipIndex(long value) {
                this.mipIndex = value;
            }

            /**
             * Gets the value of the arrayIndex property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public long getArrayIndex() {
                if (arrayIndex == null) {
                    return  0L;
                } else {
                    return arrayIndex;
                }
            }

            /**
             * Sets the value of the arrayIndex property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setArrayIndex(Long value) {
                this.arrayIndex = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SizeExact {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long width;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long height;

            /**
             * Gets the value of the width property.
             * 
             */
            public long getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(long value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             */
            public long getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             */
            public void setHeight(long value) {
                this.height = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SizeRatio {

            @XmlAttribute(required = true)
            protected float width;
            @XmlAttribute(required = true)
            protected float height;

            /**
             * Gets the value of the width property.
             * 
             */
            public float getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(float value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             */
            public float getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             */
            public void setHeight(float value) {
                this.height = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="size">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                 &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                 &lt;attribute name="depth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="mips" type="{http://www.collada.org/2008/03/COLLADASchema}image_mips_type"/>
     *         &lt;element name="array" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="format" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hint">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
     *                           &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
     *                           &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
     *                           &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="init_from" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
     *                 &lt;attribute name="depth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                 &lt;attribute name="mip_index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                 &lt;attribute name="array_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "size",
        "mips",
        "array",
        "format",
        "initFrom"
    })
    public static class Create3D {

        @XmlElement(required = true)
        protected ImageType.Create3D.Size size;
        @XmlElement(required = true)
        protected ImageMipsType mips;
        protected ImageType.Create3D.Array array;
        protected ImageType.Create3D.Format format;
        @XmlElement(name = "init_from")
        protected List<ImageType.Create3D.InitFrom> initFrom;

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.Create3D.Size }
         *     
         */
        public ImageType.Create3D.Size getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.Create3D.Size }
         *     
         */
        public void setSize(ImageType.Create3D.Size value) {
            this.size = value;
        }

        /**
         * Gets the value of the mips property.
         * 
         * @return
         *     possible object is
         *     {@link ImageMipsType }
         *     
         */
        public ImageMipsType getMips() {
            return mips;
        }

        /**
         * Sets the value of the mips property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageMipsType }
         *     
         */
        public void setMips(ImageMipsType value) {
            this.mips = value;
        }

        /**
         * Gets the value of the array property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.Create3D.Array }
         *     
         */
        public ImageType.Create3D.Array getArray() {
            return array;
        }

        /**
         * Sets the value of the array property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.Create3D.Array }
         *     
         */
        public void setArray(ImageType.Create3D.Array value) {
            this.array = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.Create3D.Format }
         *     
         */
        public ImageType.Create3D.Format getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.Create3D.Format }
         *     
         */
        public void setFormat(ImageType.Create3D.Format value) {
            this.format = value;
        }

        /**
         * Gets the value of the initFrom property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the initFrom property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInitFrom().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageType.Create3D.InitFrom }
         * 
         * 
         */
        public List<ImageType.Create3D.InitFrom> getInitFrom() {
            if (initFrom == null) {
                initFrom = new ArrayList<ImageType.Create3D.InitFrom>();
            }
            return this.initFrom;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Array {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long length;

            /**
             * Gets the value of the length property.
             * 
             */
            public long getLength() {
                return length;
            }

            /**
             * Sets the value of the length property.
             * 
             */
            public void setLength(long value) {
                this.length = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hint">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
         *                 &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
         *                 &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
         *                 &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hint",
            "exact"
        })
        public static class Format {

            @XmlElement(required = true)
            protected ImageType.Create3D.Format.Hint hint;
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String exact;

            /**
             * Gets the value of the hint property.
             * 
             * @return
             *     possible object is
             *     {@link ImageType.Create3D.Format.Hint }
             *     
             */
            public ImageType.Create3D.Format.Hint getHint() {
                return hint;
            }

            /**
             * Sets the value of the hint property.
             * 
             * @param value
             *     allowed object is
             *     {@link ImageType.Create3D.Format.Hint }
             *     
             */
            public void setHint(ImageType.Create3D.Format.Hint value) {
                this.hint = value;
            }

            /**
             * Gets the value of the exact property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExact() {
                return exact;
            }

            /**
             * Sets the value of the exact property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExact(String value) {
                this.exact = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
             *       &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
             *       &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
             *       &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Hint {

                @XmlAttribute(required = true)
                protected ImageFormatHintChannelsEnum channels;
                @XmlAttribute(required = true)
                protected ImageFormatHintRangeEnum range;
                @XmlAttribute
                protected ImageFormatHintPrecisionEnum precision;
                @XmlAttribute
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "token")
                protected String space;

                /**
                 * Gets the value of the channels property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ImageFormatHintChannelsEnum }
                 *     
                 */
                public ImageFormatHintChannelsEnum getChannels() {
                    return channels;
                }

                /**
                 * Sets the value of the channels property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ImageFormatHintChannelsEnum }
                 *     
                 */
                public void setChannels(ImageFormatHintChannelsEnum value) {
                    this.channels = value;
                }

                /**
                 * Gets the value of the range property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ImageFormatHintRangeEnum }
                 *     
                 */
                public ImageFormatHintRangeEnum getRange() {
                    return range;
                }

                /**
                 * Sets the value of the range property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ImageFormatHintRangeEnum }
                 *     
                 */
                public void setRange(ImageFormatHintRangeEnum value) {
                    this.range = value;
                }

                /**
                 * Gets the value of the precision property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ImageFormatHintPrecisionEnum }
                 *     
                 */
                public ImageFormatHintPrecisionEnum getPrecision() {
                    if (precision == null) {
                        return ImageFormatHintPrecisionEnum.DEFAULT;
                    } else {
                        return precision;
                    }
                }

                /**
                 * Sets the value of the precision property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ImageFormatHintPrecisionEnum }
                 *     
                 */
                public void setPrecision(ImageFormatHintPrecisionEnum value) {
                    this.precision = value;
                }

                /**
                 * Gets the value of the space property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSpace() {
                    return space;
                }

                /**
                 * Sets the value of the space property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSpace(String value) {
                    this.space = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
         *       &lt;attribute name="depth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *       &lt;attribute name="mip_index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *       &lt;attribute name="array_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class InitFrom
            extends ImageSourceType
        {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long depth;
            @XmlAttribute(name = "mip_index", required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long mipIndex;
            @XmlAttribute(name = "array_index")
            @XmlSchemaType(name = "unsignedInt")
            protected Long arrayIndex;

            /**
             * Gets the value of the depth property.
             * 
             */
            public long getDepth() {
                return depth;
            }

            /**
             * Sets the value of the depth property.
             * 
             */
            public void setDepth(long value) {
                this.depth = value;
            }

            /**
             * Gets the value of the mipIndex property.
             * 
             */
            public long getMipIndex() {
                return mipIndex;
            }

            /**
             * Sets the value of the mipIndex property.
             * 
             */
            public void setMipIndex(long value) {
                this.mipIndex = value;
            }

            /**
             * Gets the value of the arrayIndex property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public long getArrayIndex() {
                if (arrayIndex == null) {
                    return  0L;
                } else {
                    return arrayIndex;
                }
            }

            /**
             * Sets the value of the arrayIndex property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setArrayIndex(Long value) {
                this.arrayIndex = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *       &lt;attribute name="depth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Size {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long width;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long height;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long depth;

            /**
             * Gets the value of the width property.
             * 
             */
            public long getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(long value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             */
            public long getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             */
            public void setHeight(long value) {
                this.height = value;
            }

            /**
             * Gets the value of the depth property.
             * 
             */
            public long getDepth() {
                return depth;
            }

            /**
             * Sets the value of the depth property.
             * 
             */
            public void setDepth(long value) {
                this.depth = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="size">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="mips" type="{http://www.collada.org/2008/03/COLLADASchema}image_mips_type"/>
     *         &lt;element name="array" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="format" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hint">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
     *                           &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
     *                           &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
     *                           &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="init_from" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
     *                 &lt;attribute name="face" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_face_enum" />
     *                 &lt;attribute name="mip_index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                 &lt;attribute name="array_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "size",
        "mips",
        "array",
        "format",
        "initFrom"
    })
    public static class CreateCube {

        @XmlElement(required = true)
        protected ImageType.CreateCube.Size size;
        @XmlElement(required = true)
        protected ImageMipsType mips;
        protected ImageType.CreateCube.Array array;
        protected ImageType.CreateCube.Format format;
        @XmlElement(name = "init_from")
        protected List<ImageType.CreateCube.InitFrom> initFrom;

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.CreateCube.Size }
         *     
         */
        public ImageType.CreateCube.Size getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.CreateCube.Size }
         *     
         */
        public void setSize(ImageType.CreateCube.Size value) {
            this.size = value;
        }

        /**
         * Gets the value of the mips property.
         * 
         * @return
         *     possible object is
         *     {@link ImageMipsType }
         *     
         */
        public ImageMipsType getMips() {
            return mips;
        }

        /**
         * Sets the value of the mips property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageMipsType }
         *     
         */
        public void setMips(ImageMipsType value) {
            this.mips = value;
        }

        /**
         * Gets the value of the array property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.CreateCube.Array }
         *     
         */
        public ImageType.CreateCube.Array getArray() {
            return array;
        }

        /**
         * Sets the value of the array property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.CreateCube.Array }
         *     
         */
        public void setArray(ImageType.CreateCube.Array value) {
            this.array = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType.CreateCube.Format }
         *     
         */
        public ImageType.CreateCube.Format getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType.CreateCube.Format }
         *     
         */
        public void setFormat(ImageType.CreateCube.Format value) {
            this.format = value;
        }

        /**
         * Gets the value of the initFrom property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the initFrom property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInitFrom().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageType.CreateCube.InitFrom }
         * 
         * 
         */
        public List<ImageType.CreateCube.InitFrom> getInitFrom() {
            if (initFrom == null) {
                initFrom = new ArrayList<ImageType.CreateCube.InitFrom>();
            }
            return this.initFrom;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Array {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long length;

            /**
             * Gets the value of the length property.
             * 
             */
            public long getLength() {
                return length;
            }

            /**
             * Sets the value of the length property.
             * 
             */
            public void setLength(long value) {
                this.length = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hint">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
         *                 &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
         *                 &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
         *                 &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="exact" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hint",
            "exact"
        })
        public static class Format {

            @XmlElement(required = true)
            protected ImageType.CreateCube.Format.Hint hint;
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String exact;

            /**
             * Gets the value of the hint property.
             * 
             * @return
             *     possible object is
             *     {@link ImageType.CreateCube.Format.Hint }
             *     
             */
            public ImageType.CreateCube.Format.Hint getHint() {
                return hint;
            }

            /**
             * Sets the value of the hint property.
             * 
             * @param value
             *     allowed object is
             *     {@link ImageType.CreateCube.Format.Hint }
             *     
             */
            public void setHint(ImageType.CreateCube.Format.Hint value) {
                this.hint = value;
            }

            /**
             * Gets the value of the exact property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExact() {
                return exact;
            }

            /**
             * Sets the value of the exact property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExact(String value) {
                this.exact = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="channels" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_channels_enum" />
             *       &lt;attribute name="range" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_range_enum" />
             *       &lt;attribute name="precision" type="{http://www.collada.org/2008/03/COLLADASchema}image_format_hint_precision_enum" default="DEFAULT" />
             *       &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}token" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Hint {

                @XmlAttribute(required = true)
                protected ImageFormatHintChannelsEnum channels;
                @XmlAttribute(required = true)
                protected ImageFormatHintRangeEnum range;
                @XmlAttribute
                protected ImageFormatHintPrecisionEnum precision;
                @XmlAttribute
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "token")
                protected String space;

                /**
                 * Gets the value of the channels property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ImageFormatHintChannelsEnum }
                 *     
                 */
                public ImageFormatHintChannelsEnum getChannels() {
                    return channels;
                }

                /**
                 * Sets the value of the channels property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ImageFormatHintChannelsEnum }
                 *     
                 */
                public void setChannels(ImageFormatHintChannelsEnum value) {
                    this.channels = value;
                }

                /**
                 * Gets the value of the range property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ImageFormatHintRangeEnum }
                 *     
                 */
                public ImageFormatHintRangeEnum getRange() {
                    return range;
                }

                /**
                 * Sets the value of the range property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ImageFormatHintRangeEnum }
                 *     
                 */
                public void setRange(ImageFormatHintRangeEnum value) {
                    this.range = value;
                }

                /**
                 * Gets the value of the precision property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ImageFormatHintPrecisionEnum }
                 *     
                 */
                public ImageFormatHintPrecisionEnum getPrecision() {
                    if (precision == null) {
                        return ImageFormatHintPrecisionEnum.DEFAULT;
                    } else {
                        return precision;
                    }
                }

                /**
                 * Sets the value of the precision property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ImageFormatHintPrecisionEnum }
                 *     
                 */
                public void setPrecision(ImageFormatHintPrecisionEnum value) {
                    this.precision = value;
                }

                /**
                 * Gets the value of the space property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSpace() {
                    return space;
                }

                /**
                 * Sets the value of the space property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSpace(String value) {
                    this.space = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
         *       &lt;attribute name="face" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}image_face_enum" />
         *       &lt;attribute name="mip_index" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *       &lt;attribute name="array_index" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class InitFrom
            extends ImageSourceType
        {

            @XmlAttribute(required = true)
            protected ImageFaceEnum face;
            @XmlAttribute(name = "mip_index", required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long mipIndex;
            @XmlAttribute(name = "array_index")
            @XmlSchemaType(name = "unsignedInt")
            protected Long arrayIndex;

            /**
             * Gets the value of the face property.
             * 
             * @return
             *     possible object is
             *     {@link ImageFaceEnum }
             *     
             */
            public ImageFaceEnum getFace() {
                return face;
            }

            /**
             * Sets the value of the face property.
             * 
             * @param value
             *     allowed object is
             *     {@link ImageFaceEnum }
             *     
             */
            public void setFace(ImageFaceEnum value) {
                this.face = value;
            }

            /**
             * Gets the value of the mipIndex property.
             * 
             */
            public long getMipIndex() {
                return mipIndex;
            }

            /**
             * Sets the value of the mipIndex property.
             * 
             */
            public void setMipIndex(long value) {
                this.mipIndex = value;
            }

            /**
             * Gets the value of the arrayIndex property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public long getArrayIndex() {
                if (arrayIndex == null) {
                    return  0L;
                } else {
                    return arrayIndex;
                }
            }

            /**
             * Sets the value of the arrayIndex property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setArrayIndex(Long value) {
                this.arrayIndex = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Size {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long width;

            /**
             * Gets the value of the width property.
             * 
             */
            public long getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(long value) {
                this.width = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.collada.org/2008/03/COLLADASchema}image_source_type">
     *       &lt;attribute name="mips_generate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class InitFrom
        extends ImageSourceType
    {

        @XmlAttribute(name = "mips_generate")
        protected Boolean mipsGenerate;

        /**
         * Gets the value of the mipsGenerate property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isMipsGenerate() {
            if (mipsGenerate == null) {
                return true;
            } else {
                return mipsGenerate;
            }
        }

        /**
         * Sets the value of the mipsGenerate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMipsGenerate(Boolean value) {
            this.mipsGenerate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="share" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Renderable {

        @XmlAttribute(required = true)
        protected boolean share;

        /**
         * Gets the value of the share property.
         * 
         */
        public boolean isShare() {
            return share;
        }

        /**
         * Sets the value of the share property.
         * 
         */
        public void setShare(boolean value) {
            this.share = value;
        }

    }

}
