//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.27 at 09:08:35 PM MESZ 
//


package org.collada._2008._03.colladaschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *      A surfaceType defines the attributes of a surface     element. With rotate and translate the surface can be     positioned to its right location.    
 * 
 * <p>Java class for surface_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="surface_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="plane" type="{http://www.collada.org/2008/03/COLLADASchema}plane_type"/>
 *           &lt;element name="sphere" type="{http://www.collada.org/2008/03/COLLADASchema}sphere_type"/>
 *           &lt;element name="torus" type="{http://www.collada.org/2008/03/COLLADASchema}torus_type"/>
 *           &lt;element name="swept_surface" type="{http://www.collada.org/2008/03/COLLADASchema}swept_surface_type"/>
 *           &lt;element name="nurbs_surface" type="{http://www.collada.org/2008/03/COLLADASchema}nurbs_surface_type"/>
 *           &lt;element name="cone" type="{http://www.collada.org/2008/03/COLLADASchema}cone_type"/>
 *           &lt;element name="cylinder">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="radius" type="{http://www.collada.org/2008/03/COLLADASchema}float_type"/>
 *                     &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="orient" type="{http://www.collada.org/2008/03/COLLADASchema}orient_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="origin" type="{http://www.collada.org/2008/03/COLLADASchema}origin_type" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "surface_type", propOrder = {
    "plane",
    "sphere",
    "torus",
    "sweptSurface",
    "nurbsSurface",
    "cone",
    "cylinder",
    "orient",
    "origin"
})
public class SurfaceType {

    protected PlaneType plane;
    protected SphereType sphere;
    protected TorusType torus;
    @XmlElement(name = "swept_surface")
    protected SweptSurfaceType sweptSurface;
    @XmlElement(name = "nurbs_surface")
    protected NurbsSurfaceType nurbsSurface;
    protected ConeType cone;
    protected SurfaceType.Cylinder cylinder;
    protected List<OrientType> orient;
    protected OriginType origin;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sid;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;

    /**
     * Gets the value of the plane property.
     * 
     * @return
     *     possible object is
     *     {@link PlaneType }
     *     
     */
    public PlaneType getPlane() {
        return plane;
    }

    /**
     * Sets the value of the plane property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaneType }
     *     
     */
    public void setPlane(PlaneType value) {
        this.plane = value;
    }

    /**
     * Gets the value of the sphere property.
     * 
     * @return
     *     possible object is
     *     {@link SphereType }
     *     
     */
    public SphereType getSphere() {
        return sphere;
    }

    /**
     * Sets the value of the sphere property.
     * 
     * @param value
     *     allowed object is
     *     {@link SphereType }
     *     
     */
    public void setSphere(SphereType value) {
        this.sphere = value;
    }

    /**
     * Gets the value of the torus property.
     * 
     * @return
     *     possible object is
     *     {@link TorusType }
     *     
     */
    public TorusType getTorus() {
        return torus;
    }

    /**
     * Sets the value of the torus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TorusType }
     *     
     */
    public void setTorus(TorusType value) {
        this.torus = value;
    }

    /**
     * Gets the value of the sweptSurface property.
     * 
     * @return
     *     possible object is
     *     {@link SweptSurfaceType }
     *     
     */
    public SweptSurfaceType getSweptSurface() {
        return sweptSurface;
    }

    /**
     * Sets the value of the sweptSurface property.
     * 
     * @param value
     *     allowed object is
     *     {@link SweptSurfaceType }
     *     
     */
    public void setSweptSurface(SweptSurfaceType value) {
        this.sweptSurface = value;
    }

    /**
     * Gets the value of the nurbsSurface property.
     * 
     * @return
     *     possible object is
     *     {@link NurbsSurfaceType }
     *     
     */
    public NurbsSurfaceType getNurbsSurface() {
        return nurbsSurface;
    }

    /**
     * Sets the value of the nurbsSurface property.
     * 
     * @param value
     *     allowed object is
     *     {@link NurbsSurfaceType }
     *     
     */
    public void setNurbsSurface(NurbsSurfaceType value) {
        this.nurbsSurface = value;
    }

    /**
     * Gets the value of the cone property.
     * 
     * @return
     *     possible object is
     *     {@link ConeType }
     *     
     */
    public ConeType getCone() {
        return cone;
    }

    /**
     * Sets the value of the cone property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConeType }
     *     
     */
    public void setCone(ConeType value) {
        this.cone = value;
    }

    /**
     * Gets the value of the cylinder property.
     * 
     * @return
     *     possible object is
     *     {@link SurfaceType.Cylinder }
     *     
     */
    public SurfaceType.Cylinder getCylinder() {
        return cylinder;
    }

    /**
     * Sets the value of the cylinder property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurfaceType.Cylinder }
     *     
     */
    public void setCylinder(SurfaceType.Cylinder value) {
        this.cylinder = value;
    }

    /**
     * Gets the value of the orient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrientType }
     * 
     * 
     */
    public List<OrientType> getOrient() {
        if (orient == null) {
            orient = new ArrayList<OrientType>();
        }
        return this.orient;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link OriginType }
     *     
     */
    public OriginType getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginType }
     *     
     */
    public void setOrigin(OriginType value) {
        this.origin = value;
    }

    /**
     * Gets the value of the sid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSid() {
        return sid;
    }

    /**
     * Sets the value of the sid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSid(String value) {
        this.sid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="radius" type="{http://www.collada.org/2008/03/COLLADASchema}float_type"/>
     *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "radius",
        "extra"
    })
    public static class Cylinder {

        protected double radius;
        protected List<ExtraType> extra;

        /**
         * Gets the value of the radius property.
         * 
         */
        public double getRadius() {
            return radius;
        }

        /**
         * Sets the value of the radius property.
         * 
         */
        public void setRadius(double value) {
            this.radius = value;
        }

        /**
         * Gets the value of the extra property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extra property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtra().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExtraType }
         * 
         * 
         */
        public List<ExtraType> getExtra() {
            if (extra == null) {
                extra = new ArrayList<ExtraType>();
            }
            return this.extra;
        }

    }

}
